pkg = "static"
dest = "./static/"
fmt = true
tags = ""

[updater]
  enabled = false

[compression]
  compress = true
  method = "BestCompression"
  keep = false

clean = true
output = "assets.go"
noprefix = true
unexporTed = false
spread = true
lcf = true
debug = false

[[custom]]
  files = ["./templates/"]
  base = "templates/"
  prefix = ""
  tags = ""
